ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'USER_REGISTERED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PROBLEM_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CONCEPT_CREATED';
