CREATE TYPE "UserMathLevel" AS ENUM (
  'BEGINNER_PRE_UNIVERSITY',
  'EARLY_UNDERGRAD',
  'UNDERGRAD',
  'ADVANCED_UNDERGRAD',
  'GRADUATE_CONTEST',
  'RESEARCH'
);

ALTER TABLE "User" ADD COLUMN "mathLevel" "UserMathLevel";
