// Only the disposable test app and PostgreSQL database may be used by this runner.
import { chromium, expect as baseExpect } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
import { createHmac, randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import assert from "node:assert/strict";

const connection = process.env.CITATION_TEST_DATABASE_URL;
const expect = baseExpect.configure({ timeout: 20000 });
if (!connection || new URL(connection).hostname !== "127.0.0.1" || new URL(connection).port !== "55436") throw new Error("Use the isolated test database on port 55436.");
const secret = process.env.AUTH_SECRET;
if (secret !== "mathwoods-citations-local-test-secret-20260905") throw new Error("Use the test auth secret.");
const db = new PrismaClient({ datasourceUrl: connection });
const browser = await chromium.launch({ channel: "chrome", headless: true });
const baseURL = "http://127.0.0.1:3210", prefix = `bibliography-${Date.now()}`;
const errors = [], contexts = [];
mkdirSync("runtime/citation-tests", { recursive: true });
try {
  async function account(role, locale = "fr") {
    const user = await db.user.create({ data: { username: `${prefix}-${role}`, profileSlug: `${prefix}-${role}`, role, emailVerifiedAt: new Date() } });
    const token = randomUUID();
    await db.session.create({ data: { userId: user.id, tokenHash: createHmac("sha256", secret).update(token).digest("hex"), expiresAt: new Date(Date.now() + 3600000) } });
    const context = await browser.newContext({ baseURL, viewport: { width: 1280, height: 1000 } }); contexts.push(context);
    await context.addCookies([{ name: "math_woods_session", value: token, url: baseURL }, { name: "math-woods-language", value: locale, url: baseURL }]);
    const page = await context.newPage(); page.setDefaultTimeout(30000); page.on("pageerror", error => errors.push(error.message));
    return { user, context, page };
  }
  const admin = await account("ADMIN"), member = await account("USER");
  const work = await db.libraryReference.create({ data: { slug: `${prefix}-work`, dedupeKey: `${prefix}-work`, canonicalTitle: `Éléments ${prefix}`, authors: "Euclide", referenceType: "BOOK", status: "PUBLISHED" } });
  const page = admin.page;
  await page.goto("/library/references/new");
  const form = page.locator("form.library-entry-form");
  assert.equal(await form.locator("details[open]").count(), 0);
  await expect(form.locator('[name="canonicalTitle"]')).toBeVisible();
  await expect(form.locator('[name="edition"]')).not.toBeVisible();
  await form.locator('[name="canonicalTitle"]').fill(`Éléments — édition test ${prefix}`);
  await form.locator('[name="authors"]').fill("Euclide");
  assert.ok((await form.locator('[name="authors"]').boundingBox()).height < 100, "The simple author field must remain compact");
  assert.ok((await form.locator('[name="url"]').boundingBox()).height < 65, "The optional URL must remain a normal input");
  await page.screenshot({ path: "runtime/citation-tests/bibliography-minimal-fr.png", fullPage: true });
  await form.getByText("Édition et bibliographie", { exact: true }).click();
  await form.getByLabel("Rechercher l’œuvre générale (facultatif)").fill(prefix);
  await form.getByRole("button", { name: "Choisir", exact: true }).click();
  await expect(form.locator('[name="workId"]')).toHaveValue(String(work.id));
  for (const [name, value] of Object.entries({ edition: "2e édition", volume: "1", translator: "Heath, Thomas", publisher: "Cambridge", year: "1908" })) await form.locator(`[name="${name}"]`).fill(value);
  await form.getByText("BibTeX et identifiants", { exact: true }).click();
  await form.locator('[name="bibtex"]').fill("@book{broken,title={Oops}");
  await form.getByRole("button", { name: "Vérifier le BibTeX / l’export" }).click();
  await expect(form.getByRole("status")).toContainText("Syntaxe BibTeX invalide");
  await form.locator('button[name="intent"][value="draft"]').click();
  await expect(form.getByRole("alert")).toContainText("Syntaxe BibTeX invalide");
  await expect(form.locator('[name="canonicalTitle"]')).toHaveValue(`Éléments — édition test ${prefix}`);
  await expect(form.locator('[name="translator"]')).toHaveValue("Heath, Thomas");
  await expect(form.locator('[name="bibtex"]')).toHaveValue("@book{broken,title={Oops}");
  const raw = `@book{${prefix},title={{Elements}},author={Euclid},publisher={Cambridge},year={1908},volume={1}}`;
  await form.locator('[name="bibtex"]').fill(raw);
  await form.getByRole('button', { name: 'Importer vers les champs…' }).click();
  const proposal = form.getByRole('region', { name: 'Champs proposés' });
  await expect(proposal).toBeVisible();
  await expect(proposal.locator('label').filter({ hasText: 'Elements' }).getByRole('checkbox')).not.toBeChecked();
  await expect(proposal.locator('label').filter({ hasText: 'Euclid' }).getByRole('checkbox')).not.toBeChecked();
  await proposal.getByRole('button', { name: 'Appliquer les champs sélectionnés' }).click();
  await expect(form.locator('[name="canonicalTitle"]')).toHaveValue(`Éléments — édition test ${prefix}`);
  await expect(form.locator('[name="citationKey"]')).toHaveValue(prefix);
  await form.getByRole('button', { name: 'Importer vers les champs…' }).click();
  await proposal.locator('label').filter({ hasText: 'Elements' }).getByRole('checkbox').check();
  await proposal.getByRole('button', { name: 'Appliquer les champs sélectionnés' }).click();
  await expect(form.locator('[name="canonicalTitle"]')).toHaveValue('Elements');
  await form.locator('[name="canonicalTitle"]').fill(`Éléments — édition test ${prefix}`);
  await form.locator('button[name="intent"][value="draft"]').click();
  await expect(page).toHaveURL(/\/library\/references\/(?!new)[^/]+$/);
  const edition = await db.libraryReference.findUniqueOrThrow({ where: { citationKey: prefix } });
  assert.equal(edition.workId, work.id); assert.equal(edition.translator, "Heath, Thomas"); assert.equal(edition.bibtex, raw);
  await expect(page.getByText("Détails bibliographiques et BibTeX", { exact: true })).toBeVisible();
  assert.equal(await page.locator("details.library-form-section[open]").count(), 0);
  await db.libraryReference.update({ where: { id: edition.id }, data: { status: "PUBLISHED", isbn: `${prefix}-isbn` } });
  console.log("PASS: minimal French form, collapsed fields, BibTeX feedback, failed save preserves input, edition creation");

  const response = await member.context.request.get(`/api/references/search?q=${encodeURIComponent(`${prefix}-isbn`)}`);
  const found = await response.json(); assert.equal(response.status(), 200);
  assert.equal(found.references.length, 1); assert.equal(found.references[0].id, work.id); assert.equal(found.references[0].editionCount, 1);
  const editions = await (await member.context.request.get(`/api/references/search?workId=${work.id}`)).json();
  assert.equal(editions.references[0].id, edition.id);
  const hidden = await db.libraryReference.create({ data: { slug: `${prefix}-hidden`, dedupeKey: `${prefix}-hidden`, canonicalTitle: "Private edition", workId: work.id, referenceType: "BOOK", status: "DRAFT" } });
  assert.equal((await (await member.context.request.get(`/api/references/search?workId=${work.id}`)).json()).references.length, 1);
  assert.equal((await member.context.request.post("/api/references/bibtex", { data: { bibtex: raw } })).status(), 403);
  const problem = await db.problem.create({ data: { slug: prefix, title: "Éditions en test", bodyMarkdown: "Démontrer.", bodyHtml: "<p>Démontrer.</p>", authorId: member.user.id, language: "fr", thread: { create: {} } } });
  await member.page.goto(`/problems/${problem.slug}/edit`);
  await member.page.getByRole("button", { name: "Rechercher dans le catalogue" }).click();
  const dialog = member.page.getByRole("dialog", { name: "Rechercher une référence" });
  await dialog.getByLabel("Titre, auteur, ISBN ou DOI").fill(`${prefix}-isbn`);
  await dialog.getByRole("button", { name: "Voir les éditions (1)" }).click();
  await expect(dialog.getByText("Heath, Thomas", { exact: false })).toBeVisible();
  await member.page.setViewportSize({ width: 390, height: 844 });
  await member.page.screenshot({ path: "runtime/citation-tests/bibliography-editions-mobile.png", fullPage: true });
  assert.ok(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth + 1));
  await dialog.getByRole("button", { name: "Choisir", exact: true }).click();
  const card = member.page.locator(".problem-citation-card").last();
  await expect(card).toContainText("Heath, Thomas");
  assert.equal(await card.locator("details[open]").count(), 0);
  await expect(card.locator("textarea")).not.toBeVisible();
  console.log("PASS: member search groups editions, ISBN search, hidden editions excluded, mobile selection keeps details closed");

  await db.libraryReference.update({ where: { id: work.id }, data: { status: "ARCHIVED" } });
  const orphan = await (await member.context.request.get(`/api/references/search?q=${encodeURIComponent(`${prefix}-isbn`)}`)).json();
  assert.equal(orphan.references[0].id, edition.id);
  await db.libraryReference.update({ where: { id: work.id }, data: { status: "PUBLISHED" } });
  const json = await (await admin.context.request.get("/library/references/export?format=json")).json();
  assert.equal(json.find(item => item.slug === edition.slug).workSlug, work.slug);
  const bibExport = await admin.context.request.get("/library/references/export");
  assert.equal(bibExport.status(), 200);
  const exported = await bibExport.text();
  assert.ok(exported.includes(`Éléments — édition test ${prefix}`));
  assert.ok(exported.includes("translator = {Heath, Thomas}"));
  assert.equal(json.find(item => item.slug === edition.slug).originalBibtex, raw);
  await admin.context.addCookies([{ name: "math-woods-language", value: "en", url: baseURL }]);
  await page.goto(`/library/references/${edition.slug}/edit?lang=en`);
  await expect(page.getByText("Edition and bibliography", { exact: true })).toBeVisible();
  assert.equal(await page.locator("form details[open]").count(), 0);
  await page.getByText("Edition and bibliography", { exact: true }).click();
  await expect(page.locator('[name="translator"]')).toHaveValue("Heath, Thomas");
  await expect(page.getByText(work.canonicalTitle, { exact: true }).last()).toBeVisible();
  await db.libraryReference.delete({ where: { id: hidden.id } });
  console.log("PASS: archived parent fallback, JSON and BibTeX exports, English edit retains metadata and collapsed sections");
  assert.deepEqual(errors, []);
} finally {
  for (const context of contexts) await context.close();
  await browser.close(); await db.$disconnect();
}
