export const libraryCopy = {
  en: {
    title: "Library",
    description: "People, milestones, and references that place mathematics in its wider story.",
    overview: "Overview",
    history: "History",
    mathematicians: "Mathematicians",
    references: "References",
    contribution: "Contribute",
    featuredHistory: "A moment in mathematical history",
    featuredMathematician: "A mathematician",
    featuredReference: "A reference to explore",
    browseAll: "Browse all",
    add: "Add",
    edit: "Edit",
    review: "Review",
    saveDraft: "Save draft",
    submit: "Submit for review",
    publish: "Publish",
    requestChanges: "Request changes",
    reviewNote: "What needs to be changed?",
    reviewNotePlaceholder: "Give the contributor a short, actionable explanation.",
    archive: "Archive",
    restore: "Restore as needs work",
    requestedChanges: "Reviewer feedback",
    noEntries: "Nothing has been published here yet.",
    imageCredit: "Image credit"
  },
  fr: {
    title: "Bibliothèque",
    description: "Les personnes, les repères historiques et les références qui donnent aux mathématiques un contexte plus large.",
    overview: "Accueil",
    history: "Histoire",
    mathematicians: "Mathématiciens",
    references: "Références",
    contribution: "Contribuer",
    featuredHistory: "Un moment de l’histoire des mathématiques",
    featuredMathematician: "Un mathématicien",
    featuredReference: "Une référence à découvrir",
    browseAll: "Tout parcourir",
    add: "Ajouter",
    edit: "Modifier",
    review: "Relire",
    saveDraft: "Enregistrer le brouillon",
    submit: "Envoyer en relecture",
    publish: "Publier",
    requestChanges: "Demander des modifications",
    reviewNote: "Que faut-il modifier ?",
    reviewNotePlaceholder: "Donnez une explication courte et directement exploitable.",
    archive: "Archiver",
    restore: "Restaurer comme fiche à retravailler",
    requestedChanges: "Retour de la relecture",
    noEntries: "Rien n’a encore été publié ici.",
    imageCredit: "Crédit de l’image"
  }
} as const;
